import = ["/home/staal/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[window.padding]
x = 5
y = 5
