#!/bin/bash
#
# a simple dmenu session script 
#
###

DMENU='dmenu -l 20 -nf #f8f8f2 -nb #20212b -sf #f8f8f2 -sb #44475a'
choice=$(echo -e "shutdown\nreboot" | $DMENU)

case "$choice" in
  shutdown) sudo shutdown -h now & ;;
  reboot) sudo shutdown -r now & ;;
esac
