import = ["/home/staal/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[window.padding]
x = 5
y = 5
